# Generated by Django 6.0.3 on 2026-03-22 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название экскурсии')),
                ('description', models.TextField(verbose_name='Описание')),
                ('guide_name', models.CharField(blank=True, max_length=255, verbose_name='Имя гида')),
                ('start_datetime', models.DateTimeField(verbose_name='Дата и время начала')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='Длительность в минутах')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('max_people', models.PositiveIntegerField(verbose_name='Максимум человек')),
                ('booked_people', models.PositiveIntegerField(default=0, verbose_name='Забронировано мест')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликована'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excursions', to='places.place', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'Экскурсия',
                'verbose_name_plural': 'Экскурсии',
                'ordering': ['start_datetime'],
            },
        ),
    ]
